export { DashboardPage } from "./pages/dashboard";
export { TenantsPage } from "./pages/tenants";
export { OrdersPage, OrderFulfillmentPage } from "./pages/orders";
export { CatalogPage } from "./pages/catalog";
export { InventoryPage } from "./pages/inventory";
export { KitsPage } from "./pages/kits";
export { ShipmentsPage } from "./pages/shipments";
export { SupportPage } from "./pages/support";
export { ProductionPage } from "./pages/production";
export { FinancePage } from "./pages/finance";
export { TeamPage } from "./pages/team";
export { AuditPage } from "./pages/audit";
export { SettingsPage } from "./pages/settings";
export { PlatformIndexRedirect } from "./pages/index-redirect";
