/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as RedeemTokenRouteImport } from './routes/redeem.$token'
import { Route as PlatformTenantsRouteImport } from './routes/platform.tenants'
import { Route as PlatformTeamRouteImport } from './routes/platform.team'
import { Route as PlatformSupportRouteImport } from './routes/platform.support'
import { Route as PlatformShipmentsRouteImport } from './routes/platform.shipments'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformProductionRouteImport } from './routes/platform.production'
import { Route as PlatformOrdersRouteImport } from './routes/platform.orders'
import { Route as PlatformKitsRouteImport } from './routes/platform.kits'
import { Route as PlatformInventoryRouteImport } from './routes/platform.inventory'
import { Route as PlatformFinanceRouteImport } from './routes/platform.finance'
import { Route as PlatformDashboardRouteImport } from './routes/platform.dashboard'
import { Route as PlatformCatalogRouteImport } from './routes/platform.catalog'
import { Route as PlatformAuditRouteImport } from './routes/platform.audit'
import { Route as AppWalletsRouteImport } from './routes/app.wallets'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as PlatformOrdersIndexRouteImport } from './routes/platform.orders.index'
import { Route as PlatformKitsIndexRouteImport } from './routes/platform.kits.index'
import { Route as PlatformCatalogIndexRouteImport } from './routes/platform.catalog.index'
import { Route as AppSwagIndexRouteImport } from './routes/app.swag.index'
import { Route as AppShopsIndexRouteImport } from './routes/app.shops.index'
import { Route as PlatformOrdersIdRouteImport } from './routes/platform.orders.$id'
import { Route as PlatformKitsNewRouteImport } from './routes/platform.kits.new'
import { Route as PlatformKitsImportRouteImport } from './routes/platform.kits.import'
import { Route as PlatformKitsIdRouteImport } from './routes/platform.kits.$id'
import { Route as PlatformCatalogNewRouteImport } from './routes/platform.catalog.new'
import { Route as PlatformCatalogImportRouteImport } from './routes/platform.catalog.import'
import { Route as PlatformCatalogIdRouteImport } from './routes/platform.catalog.$id'
import { Route as AppSwagNewRouteImport } from './routes/app.swag.new'
import { Route as AppShopsNewRouteImport } from './routes/app.shops.new'
import { Route as AppShopsIdRouteImport } from './routes/app.shops.$id'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemTokenRoute = RedeemTokenRouteImport.update({
  id: '/redeem/$token',
  path: '/redeem/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTenantsRoute = PlatformTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformTeamRoute = PlatformTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformShipmentsRoute = PlatformShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformProductionRoute = PlatformProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOrdersRoute = PlatformOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformKitsRoute = PlatformKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInventoryRoute = PlatformInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFinanceRoute = PlatformFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCatalogRoute = PlatformCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const PlatformOrdersIndexRoute = PlatformOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformOrdersRoute,
} as any)
const PlatformKitsIndexRoute = PlatformKitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformKitsRoute,
} as any)
const PlatformCatalogIndexRoute = PlatformCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformCatalogRoute,
} as any)
const AppSwagIndexRoute = AppSwagIndexRouteImport.update({
  id: '/swag/',
  path: '/swag/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsIndexRoute = AppShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => AppRoute,
} as any)
const PlatformOrdersIdRoute = PlatformOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlatformOrdersRoute,
} as any)
const PlatformKitsNewRoute = PlatformKitsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlatformKitsRoute,
} as any)
const PlatformKitsImportRoute = PlatformKitsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PlatformKitsRoute,
} as any)
const PlatformKitsIdRoute = PlatformKitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlatformKitsRoute,
} as any)
const PlatformCatalogNewRoute = PlatformCatalogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlatformCatalogRoute,
} as any)
const PlatformCatalogImportRoute = PlatformCatalogImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PlatformCatalogRoute,
} as any)
const PlatformCatalogIdRoute = PlatformCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlatformCatalogRoute,
} as any)
const AppSwagNewRoute = AppSwagNewRouteImport.update({
  id: '/swag/new',
  path: '/swag/new',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsNewRoute = AppShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsIdRoute = AppShopsIdRouteImport.update({
  id: '/shops/$id',
  path: '/shops/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/catalog': typeof PlatformCatalogRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/finance': typeof PlatformFinanceRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/kits': typeof PlatformKitsRouteWithChildren
  '/platform/orders': typeof PlatformOrdersRouteWithChildren
  '/platform/production': typeof PlatformProductionRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/shipments': typeof PlatformShipmentsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/team': typeof PlatformTeamRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/redeem/$token': typeof RedeemTokenRoute
  '/shop/$id': typeof ShopIdRoute
  '/app/': typeof AppIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/app/shops/$id': typeof AppShopsIdRoute
  '/app/shops/new': typeof AppShopsNewRoute
  '/app/swag/new': typeof AppSwagNewRoute
  '/platform/catalog/$id': typeof PlatformCatalogIdRoute
  '/platform/catalog/import': typeof PlatformCatalogImportRoute
  '/platform/catalog/new': typeof PlatformCatalogNewRoute
  '/platform/kits/$id': typeof PlatformKitsIdRoute
  '/platform/kits/import': typeof PlatformKitsImportRoute
  '/platform/kits/new': typeof PlatformKitsNewRoute
  '/platform/orders/$id': typeof PlatformOrdersIdRoute
  '/app/shops/': typeof AppShopsIndexRoute
  '/app/swag/': typeof AppSwagIndexRoute
  '/platform/catalog/': typeof PlatformCatalogIndexRoute
  '/platform/kits/': typeof PlatformKitsIndexRoute
  '/platform/orders/': typeof PlatformOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/finance': typeof PlatformFinanceRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/production': typeof PlatformProductionRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/shipments': typeof PlatformShipmentsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/team': typeof PlatformTeamRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/redeem/$token': typeof RedeemTokenRoute
  '/shop/$id': typeof ShopIdRoute
  '/app': typeof AppIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/app/shops/$id': typeof AppShopsIdRoute
  '/app/shops/new': typeof AppShopsNewRoute
  '/app/swag/new': typeof AppSwagNewRoute
  '/platform/catalog/$id': typeof PlatformCatalogIdRoute
  '/platform/catalog/import': typeof PlatformCatalogImportRoute
  '/platform/catalog/new': typeof PlatformCatalogNewRoute
  '/platform/kits/$id': typeof PlatformKitsIdRoute
  '/platform/kits/import': typeof PlatformKitsImportRoute
  '/platform/kits/new': typeof PlatformKitsNewRoute
  '/platform/orders/$id': typeof PlatformOrdersIdRoute
  '/app/shops': typeof AppShopsIndexRoute
  '/app/swag': typeof AppSwagIndexRoute
  '/platform/catalog': typeof PlatformCatalogIndexRoute
  '/platform/kits': typeof PlatformKitsIndexRoute
  '/platform/orders': typeof PlatformOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/catalog': typeof PlatformCatalogRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/finance': typeof PlatformFinanceRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/kits': typeof PlatformKitsRouteWithChildren
  '/platform/orders': typeof PlatformOrdersRouteWithChildren
  '/platform/production': typeof PlatformProductionRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/shipments': typeof PlatformShipmentsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/team': typeof PlatformTeamRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/redeem/$token': typeof RedeemTokenRoute
  '/shop/$id': typeof ShopIdRoute
  '/app/': typeof AppIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/app/shops/$id': typeof AppShopsIdRoute
  '/app/shops/new': typeof AppShopsNewRoute
  '/app/swag/new': typeof AppSwagNewRoute
  '/platform/catalog/$id': typeof PlatformCatalogIdRoute
  '/platform/catalog/import': typeof PlatformCatalogImportRoute
  '/platform/catalog/new': typeof PlatformCatalogNewRoute
  '/platform/kits/$id': typeof PlatformKitsIdRoute
  '/platform/kits/import': typeof PlatformKitsImportRoute
  '/platform/kits/new': typeof PlatformKitsNewRoute
  '/platform/orders/$id': typeof PlatformOrdersIdRoute
  '/app/shops/': typeof AppShopsIndexRoute
  '/app/swag/': typeof AppSwagIndexRoute
  '/platform/catalog/': typeof PlatformCatalogIndexRoute
  '/platform/kits/': typeof PlatformKitsIndexRoute
  '/platform/orders/': typeof PlatformOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/app'
    | '/platform'
    | '/app/catalog'
    | '/app/contacts'
    | '/app/orders'
    | '/app/settings'
    | '/app/wallets'
    | '/platform/audit'
    | '/platform/catalog'
    | '/platform/dashboard'
    | '/platform/finance'
    | '/platform/inventory'
    | '/platform/kits'
    | '/platform/orders'
    | '/platform/production'
    | '/platform/settings'
    | '/platform/shipments'
    | '/platform/support'
    | '/platform/team'
    | '/platform/tenants'
    | '/redeem/$token'
    | '/shop/$id'
    | '/app/'
    | '/platform/'
    | '/app/shops/$id'
    | '/app/shops/new'
    | '/app/swag/new'
    | '/platform/catalog/$id'
    | '/platform/catalog/import'
    | '/platform/catalog/new'
    | '/platform/kits/$id'
    | '/platform/kits/import'
    | '/platform/kits/new'
    | '/platform/orders/$id'
    | '/app/shops/'
    | '/app/swag/'
    | '/platform/catalog/'
    | '/platform/kits/'
    | '/platform/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/app/catalog'
    | '/app/contacts'
    | '/app/orders'
    | '/app/settings'
    | '/app/wallets'
    | '/platform/audit'
    | '/platform/dashboard'
    | '/platform/finance'
    | '/platform/inventory'
    | '/platform/production'
    | '/platform/settings'
    | '/platform/shipments'
    | '/platform/support'
    | '/platform/team'
    | '/platform/tenants'
    | '/redeem/$token'
    | '/shop/$id'
    | '/app'
    | '/platform'
    | '/app/shops/$id'
    | '/app/shops/new'
    | '/app/swag/new'
    | '/platform/catalog/$id'
    | '/platform/catalog/import'
    | '/platform/catalog/new'
    | '/platform/kits/$id'
    | '/platform/kits/import'
    | '/platform/kits/new'
    | '/platform/orders/$id'
    | '/app/shops'
    | '/app/swag'
    | '/platform/catalog'
    | '/platform/kits'
    | '/platform/orders'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/app'
    | '/platform'
    | '/app/catalog'
    | '/app/contacts'
    | '/app/orders'
    | '/app/settings'
    | '/app/wallets'
    | '/platform/audit'
    | '/platform/catalog'
    | '/platform/dashboard'
    | '/platform/finance'
    | '/platform/inventory'
    | '/platform/kits'
    | '/platform/orders'
    | '/platform/production'
    | '/platform/settings'
    | '/platform/shipments'
    | '/platform/support'
    | '/platform/team'
    | '/platform/tenants'
    | '/redeem/$token'
    | '/shop/$id'
    | '/app/'
    | '/platform/'
    | '/app/shops/$id'
    | '/app/shops/new'
    | '/app/swag/new'
    | '/platform/catalog/$id'
    | '/platform/catalog/import'
    | '/platform/catalog/new'
    | '/platform/kits/$id'
    | '/platform/kits/import'
    | '/platform/kits/new'
    | '/platform/orders/$id'
    | '/app/shops/'
    | '/app/swag/'
    | '/platform/catalog/'
    | '/platform/kits/'
    | '/platform/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  RedeemTokenRoute: typeof RedeemTokenRoute
  ShopIdRoute: typeof ShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem/$token': {
      id: '/redeem/$token'
      path: '/redeem/$token'
      fullPath: '/redeem/$token'
      preLoaderRoute: typeof RedeemTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/tenants': {
      id: '/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/team': {
      id: '/platform/team'
      path: '/team'
      fullPath: '/platform/team'
      preLoaderRoute: typeof PlatformTeamRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/support': {
      id: '/platform/support'
      path: '/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/shipments': {
      id: '/platform/shipments'
      path: '/shipments'
      fullPath: '/platform/shipments'
      preLoaderRoute: typeof PlatformShipmentsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/production': {
      id: '/platform/production'
      path: '/production'
      fullPath: '/platform/production'
      preLoaderRoute: typeof PlatformProductionRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/orders': {
      id: '/platform/orders'
      path: '/orders'
      fullPath: '/platform/orders'
      preLoaderRoute: typeof PlatformOrdersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/kits': {
      id: '/platform/kits'
      path: '/kits'
      fullPath: '/platform/kits'
      preLoaderRoute: typeof PlatformKitsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/inventory': {
      id: '/platform/inventory'
      path: '/inventory'
      fullPath: '/platform/inventory'
      preLoaderRoute: typeof PlatformInventoryRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/finance': {
      id: '/platform/finance'
      path: '/finance'
      fullPath: '/platform/finance'
      preLoaderRoute: typeof PlatformFinanceRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/catalog': {
      id: '/platform/catalog'
      path: '/catalog'
      fullPath: '/platform/catalog'
      preLoaderRoute: typeof PlatformCatalogRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/wallets': {
      id: '/app/wallets'
      path: '/wallets'
      fullPath: '/app/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/orders/': {
      id: '/platform/orders/'
      path: '/'
      fullPath: '/platform/orders/'
      preLoaderRoute: typeof PlatformOrdersIndexRouteImport
      parentRoute: typeof PlatformOrdersRoute
    }
    '/platform/kits/': {
      id: '/platform/kits/'
      path: '/'
      fullPath: '/platform/kits/'
      preLoaderRoute: typeof PlatformKitsIndexRouteImport
      parentRoute: typeof PlatformKitsRoute
    }
    '/platform/catalog/': {
      id: '/platform/catalog/'
      path: '/'
      fullPath: '/platform/catalog/'
      preLoaderRoute: typeof PlatformCatalogIndexRouteImport
      parentRoute: typeof PlatformCatalogRoute
    }
    '/app/swag/': {
      id: '/app/swag/'
      path: '/swag'
      fullPath: '/app/swag/'
      preLoaderRoute: typeof AppSwagIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shops/': {
      id: '/app/shops/'
      path: '/shops'
      fullPath: '/app/shops/'
      preLoaderRoute: typeof AppShopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/orders/$id': {
      id: '/platform/orders/$id'
      path: '/$id'
      fullPath: '/platform/orders/$id'
      preLoaderRoute: typeof PlatformOrdersIdRouteImport
      parentRoute: typeof PlatformOrdersRoute
    }
    '/platform/kits/new': {
      id: '/platform/kits/new'
      path: '/new'
      fullPath: '/platform/kits/new'
      preLoaderRoute: typeof PlatformKitsNewRouteImport
      parentRoute: typeof PlatformKitsRoute
    }
    '/platform/kits/import': {
      id: '/platform/kits/import'
      path: '/import'
      fullPath: '/platform/kits/import'
      preLoaderRoute: typeof PlatformKitsImportRouteImport
      parentRoute: typeof PlatformKitsRoute
    }
    '/platform/kits/$id': {
      id: '/platform/kits/$id'
      path: '/$id'
      fullPath: '/platform/kits/$id'
      preLoaderRoute: typeof PlatformKitsIdRouteImport
      parentRoute: typeof PlatformKitsRoute
    }
    '/platform/catalog/new': {
      id: '/platform/catalog/new'
      path: '/new'
      fullPath: '/platform/catalog/new'
      preLoaderRoute: typeof PlatformCatalogNewRouteImport
      parentRoute: typeof PlatformCatalogRoute
    }
    '/platform/catalog/import': {
      id: '/platform/catalog/import'
      path: '/import'
      fullPath: '/platform/catalog/import'
      preLoaderRoute: typeof PlatformCatalogImportRouteImport
      parentRoute: typeof PlatformCatalogRoute
    }
    '/platform/catalog/$id': {
      id: '/platform/catalog/$id'
      path: '/$id'
      fullPath: '/platform/catalog/$id'
      preLoaderRoute: typeof PlatformCatalogIdRouteImport
      parentRoute: typeof PlatformCatalogRoute
    }
    '/app/swag/new': {
      id: '/app/swag/new'
      path: '/swag/new'
      fullPath: '/app/swag/new'
      preLoaderRoute: typeof AppSwagNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shops/new': {
      id: '/app/shops/new'
      path: '/shops/new'
      fullPath: '/app/shops/new'
      preLoaderRoute: typeof AppShopsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shops/$id': {
      id: '/app/shops/$id'
      path: '/shops/$id'
      fullPath: '/app/shops/$id'
      preLoaderRoute: typeof AppShopsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogRoute: typeof AppCatalogRoute
  AppContactsRoute: typeof AppContactsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppShopsIdRoute: typeof AppShopsIdRoute
  AppShopsNewRoute: typeof AppShopsNewRoute
  AppSwagNewRoute: typeof AppSwagNewRoute
  AppShopsIndexRoute: typeof AppShopsIndexRoute
  AppSwagIndexRoute: typeof AppSwagIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogRoute: AppCatalogRoute,
  AppContactsRoute: AppContactsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppIndexRoute: AppIndexRoute,
  AppShopsIdRoute: AppShopsIdRoute,
  AppShopsNewRoute: AppShopsNewRoute,
  AppSwagNewRoute: AppSwagNewRoute,
  AppShopsIndexRoute: AppShopsIndexRoute,
  AppSwagIndexRoute: AppSwagIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformCatalogRouteChildren {
  PlatformCatalogIdRoute: typeof PlatformCatalogIdRoute
  PlatformCatalogImportRoute: typeof PlatformCatalogImportRoute
  PlatformCatalogNewRoute: typeof PlatformCatalogNewRoute
  PlatformCatalogIndexRoute: typeof PlatformCatalogIndexRoute
}

const PlatformCatalogRouteChildren: PlatformCatalogRouteChildren = {
  PlatformCatalogIdRoute: PlatformCatalogIdRoute,
  PlatformCatalogImportRoute: PlatformCatalogImportRoute,
  PlatformCatalogNewRoute: PlatformCatalogNewRoute,
  PlatformCatalogIndexRoute: PlatformCatalogIndexRoute,
}

const PlatformCatalogRouteWithChildren = PlatformCatalogRoute._addFileChildren(
  PlatformCatalogRouteChildren,
)

interface PlatformKitsRouteChildren {
  PlatformKitsIdRoute: typeof PlatformKitsIdRoute
  PlatformKitsImportRoute: typeof PlatformKitsImportRoute
  PlatformKitsNewRoute: typeof PlatformKitsNewRoute
  PlatformKitsIndexRoute: typeof PlatformKitsIndexRoute
}

const PlatformKitsRouteChildren: PlatformKitsRouteChildren = {
  PlatformKitsIdRoute: PlatformKitsIdRoute,
  PlatformKitsImportRoute: PlatformKitsImportRoute,
  PlatformKitsNewRoute: PlatformKitsNewRoute,
  PlatformKitsIndexRoute: PlatformKitsIndexRoute,
}

const PlatformKitsRouteWithChildren = PlatformKitsRoute._addFileChildren(
  PlatformKitsRouteChildren,
)

interface PlatformOrdersRouteChildren {
  PlatformOrdersIdRoute: typeof PlatformOrdersIdRoute
  PlatformOrdersIndexRoute: typeof PlatformOrdersIndexRoute
}

const PlatformOrdersRouteChildren: PlatformOrdersRouteChildren = {
  PlatformOrdersIdRoute: PlatformOrdersIdRoute,
  PlatformOrdersIndexRoute: PlatformOrdersIndexRoute,
}

const PlatformOrdersRouteWithChildren = PlatformOrdersRoute._addFileChildren(
  PlatformOrdersRouteChildren,
)

interface PlatformRouteChildren {
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformCatalogRoute: typeof PlatformCatalogRouteWithChildren
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformFinanceRoute: typeof PlatformFinanceRoute
  PlatformInventoryRoute: typeof PlatformInventoryRoute
  PlatformKitsRoute: typeof PlatformKitsRouteWithChildren
  PlatformOrdersRoute: typeof PlatformOrdersRouteWithChildren
  PlatformProductionRoute: typeof PlatformProductionRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformShipmentsRoute: typeof PlatformShipmentsRoute
  PlatformSupportRoute: typeof PlatformSupportRoute
  PlatformTeamRoute: typeof PlatformTeamRoute
  PlatformTenantsRoute: typeof PlatformTenantsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformCatalogRoute: PlatformCatalogRouteWithChildren,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformFinanceRoute: PlatformFinanceRoute,
  PlatformInventoryRoute: PlatformInventoryRoute,
  PlatformKitsRoute: PlatformKitsRouteWithChildren,
  PlatformOrdersRoute: PlatformOrdersRouteWithChildren,
  PlatformProductionRoute: PlatformProductionRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformShipmentsRoute: PlatformShipmentsRoute,
  PlatformSupportRoute: PlatformSupportRoute,
  PlatformTeamRoute: PlatformTeamRoute,
  PlatformTenantsRoute: PlatformTenantsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  RedeemTokenRoute: RedeemTokenRoute,
  ShopIdRoute: ShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
