/** Mirrors apps/web/src/lib/shelf-merch.js DEMO_PRODUCTS — enriched for platform catalog demos. */
export const CATALOG_PRODUCTS = [
  {
    sku: 'SM-TEE-001',
    brand: 'Port & Company',
    name: 'Youth Core Cotton Tee',
    category: 'Apparel',
    group: 'tee',
    basePriceInr: 180,
    costPriceInr: 85,
    supplierName: 'PrintCraft India',
    gstRate: 12,
    hsnCode: '6109',
    material: '100% cotton',
    printableAreas: ['front', 'back'],
    customizationMethods: ['screen_print', 'dtf'],
    productionDays: 5,
    inventory: { mode: 'physical', available: 250, reserved: 12, lowStockThreshold: 20 },
    status: 'active',
  },
  {
    sku: 'SM-HOOD-001',
    brand: 'Bella + Canvas',
    name: 'Sponge Fleece Pullover Hoodie',
    category: 'Apparel',
    group: 'hoodie',
    basePriceInr: 1150,
    costPriceInr: 520,
    supplierName: 'PrintCraft India',
    gstRate: 12,
    hsnCode: '6110',
    material: 'Cotton/poly fleece',
    printableAreas: ['front', 'sleeve'],
    customizationMethods: ['embroidery', 'dtf'],
    productionDays: 7,
    inventory: { mode: 'physical', available: 80, reserved: 5, lowStockThreshold: 15 },
    status: 'active',
  },
  {
    sku: 'SM-BTL-001',
    brand: '',
    name: 'The Standard Bottle',
    category: 'Drinkware',
    group: 'bottle',
    basePriceInr: 890,
    costPriceInr: 410,
    supplierName: 'BoxWise Packaging',
    gstRate: 18,
    hsnCode: '7323',
    inventory: { mode: 'physical', available: 120, reserved: 0, lowStockThreshold: 25 },
    status: 'active',
  },
  {
    sku: 'SM-MUG-001',
    brand: '',
    name: 'Black Glossy Mug 11oz',
    category: 'Drinkware',
    group: 'mug',
    basePriceInr: 420,
    costPriceInr: 190,
    gstRate: 18,
    hsnCode: '6912',
    customizationMethods: ['sublimation'],
    inventory: { mode: 'physical', available: 200, reserved: 8, lowStockThreshold: 30 },
    status: 'active',
  },
  {
    sku: 'SM-PACK-001',
    brand: 'Mercer+Mettle',
    name: 'Commuter Backpack',
    category: 'Bags',
    group: 'pack',
    basePriceInr: 3400,
    costPriceInr: 1800,
    gstRate: 18,
    hsnCode: '4202',
    inventory: { mode: 'made_to_order', available: 0, reserved: 0, lowStockThreshold: 0 },
    status: 'active',
  },
  {
    sku: 'SM-CAP-001',
    brand: 'Decathlon',
    name: 'Structured Twill Cap',
    category: 'Apparel',
    group: 'cap',
    basePriceInr: 640,
    costPriceInr: 290,
    gstRate: 12,
    hsnCode: '6505',
    inventory: { mode: 'physical', available: 8, reserved: 2, lowStockThreshold: 10 },
    status: 'active',
  },
  {
    sku: 'SM-NOTE-001',
    brand: 'Moleskine',
    name: 'Classic Hard Notebook',
    category: 'Office',
    group: 'note',
    basePriceInr: 1120,
    costPriceInr: 680,
    gstRate: 18,
    hsnCode: '4820',
    inventory: { mode: 'physical', available: 45, reserved: 0, lowStockThreshold: 10 },
    status: 'active',
  },
  {
    sku: 'SM-PWR-001',
    brand: 'Ambrane',
    name: 'Xtreme-10 Power Bank',
    category: 'Technology',
    group: 'power',
    basePriceInr: 1426,
    costPriceInr: 950,
    gstRate: 18,
    hsnCode: '8507',
    inventory: { mode: 'physical', available: 60, reserved: 3, lowStockThreshold: 15 },
    status: 'active',
  },
  {
    sku: 'SM-PIL-001',
    brand: '',
    name: 'Travel Neck Pillow',
    category: 'Merch',
    group: 'pillow',
    basePriceInr: 540,
    costPriceInr: 240,
    gstRate: 18,
    hsnCode: '9404',
    inventory: { mode: 'physical', available: 35, reserved: 0, lowStockThreshold: 10 },
    status: 'active',
  },
  {
    sku: 'SM-BAG-001',
    brand: 'ChangeBag',
    name: 'Organic Canvas Tote',
    category: 'Bags',
    group: 'bag',
    basePriceInr: 360,
    costPriceInr: 165,
    gstRate: 18,
    hsnCode: '4202',
    inventory: { mode: 'physical', available: 300, reserved: 20, lowStockThreshold: 40 },
    status: 'active',
  },
  {
    sku: 'SM-TEE-002',
    brand: 'Comfort Colors',
    name: 'Garment-Dyed Heavyweight Tee',
    category: 'Apparel',
    group: 'tee',
    basePriceInr: 1640,
    costPriceInr: 780,
    gstRate: 12,
    hsnCode: '6109',
    inventory: { mode: 'made_to_order', available: 0, reserved: 0, lowStockThreshold: 0 },
    status: 'active',
  },
  {
    sku: 'SM-BTL-002',
    brand: 'DeskMate',
    name: 'Steel Bottle 750ml',
    category: 'Drinkware',
    group: 'bottle',
    basePriceInr: 689,
    costPriceInr: 310,
    gstRate: 18,
    hsnCode: '7323',
    inventory: { mode: 'physical', available: 18, reserved: 0, lowStockThreshold: 20 },
    status: 'active',
  },
];
